// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwP2r39KdRERQhgqJb7oBGEEunNSYv5oY',
    appId: '1:920150322072:web:5b0b47f9310bd30b7e99ed',
    messagingSenderId: '920150322072',
    projectId: 'exp-appvd',
    authDomain: 'exp-appvd.firebaseapp.com',
    storageBucket: 'exp-appvd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPtgKrf6UTfHrM3_M76q3Fbg_6mCYa9MU',
    appId: '1:920150322072:android:2221e8e08a5b57a37e99ed',
    messagingSenderId: '920150322072',
    projectId: 'exp-appvd',
    storageBucket: 'exp-appvd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXy9Z_qNHABeWnwuvph2V6DZoMcfO6C0c',
    appId: '1:920150322072:ios:7e1a19d7c1e887c27e99ed',
    messagingSenderId: '920150322072',
    projectId: 'exp-appvd',
    storageBucket: 'exp-appvd.firebasestorage.app',
    iosBundleId: 'com.mashiur.expenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXy9Z_qNHABeWnwuvph2V6DZoMcfO6C0c',
    appId: '1:920150322072:ios:6630b45e4697ed9c7e99ed',
    messagingSenderId: '920150322072',
    projectId: 'exp-appvd',
    storageBucket: 'exp-appvd.firebasestorage.app',
    iosBundleId: 'com.example.yourExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwP2r39KdRERQhgqJb7oBGEEunNSYv5oY',
    appId: '1:920150322072:web:1841066058d9b9b27e99ed',
    messagingSenderId: '920150322072',
    projectId: 'exp-appvd',
    authDomain: 'exp-appvd.firebaseapp.com',
    storageBucket: 'exp-appvd.firebasestorage.app',
  );
}
